app/routes.php
<?php

Route::get('/', 'HomeController@showWelcome');

Route::resource('user', 'UserController');

Route::get('user/{user}/delete', [
	'uses' => 'UserController@delete',
	'as'   => 'user.delete'
]);

app/filters.php
<?php

/*
|--------------------------------------------------------------------------
| Application & Route Filters
|--------------------------------------------------------------------------
|
| Below you will find the "before" and "after" events for the application
| which may be used to do any work before or after a request into your
| application. Here you may also register your custom route filters.
|
*/

App::before(function($request)
{
	//
});


App::after(function($request, $response)
{
	//
});

/*
|--------------------------------------------------------------------------
| Authentication Filters
|--------------------------------------------------------------------------
|
| The following filters are used to verify that the user of the current
| session is logged into this application. The "basic" filter easily
| integrates HTTP Basic authentication for quick, simple checking.
|
*/

Route::filter('auth', function()
{
	if (Auth::guest())
	{
		if (Request::ajax())
		{
			return Response::make('Unauthorized', 401);
		}
		else
		{
			return Redirect::guest('login');
		}
	}
});


Route::filter('auth.basic', function()
{
	return Auth::basic();
});

/*
|--------------------------------------------------------------------------
| Guest Filter
|--------------------------------------------------------------------------
|
| The "guest" filter is the counterpart of the authentication filters as
| it simply checks that the current user is not logged in. A redirect
| response will be issued if they are, which you may freely change.
|
*/

Route::filter('guest', function()
{
	if (Auth::check()) return Redirect::to('/');
});

/*
|--------------------------------------------------------------------------
| CSRF Protection Filter
|--------------------------------------------------------------------------
|
| The CSRF filter is responsible for protecting your application against
| cross-site request forgery attacks. If this special token in a user
| session does not match the one given in this request, we'll bail.
|
*/

Route::filter('csrf', function()
{
	if (Session::token() != Input::get('_token'))
	{
		throw new Illuminate\Session\TokenMismatchException;
	}
});

app/models/User.php
<?php

use Illuminate\Auth\UserTrait;
use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableTrait;
use Illuminate\Auth\Reminders\RemindableInterface;

class User extends Eloquent implements UserInterface, RemindableInterface {

	use UserTrait, RemindableTrait;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password', 'remember_token');

	protected $fillable = [
		'name', 'email', 'password'
	];

}

app/controllers/BaseController.php
<?php

class BaseController extends Controller {

	/**
	 * Setup the layout used by the controller.
	 *
	 * @return void
	 */
	protected function setupLayout()
	{
		if ( ! is_null($this->layout))
		{
			$this->layout = View::make($this->layout);
		}
	}

}

app/controllers/HomeController.php
<?php

class HomeController extends BaseController {

	/*
	|--------------------------------------------------------------------------
	| Default Home Controller
	|--------------------------------------------------------------------------
	|
	| You may wish to use controllers instead of, or in addition to, Closure
	| based routes. That's great! Here is an example controller method to
	| get you started. To route to this controller, just add the route:
	|
	|	Route::get('/', 'HomeController@showWelcome');
	|
	*/

	public function showWelcome()
	{
		return View::make('hello');
	}

}

app/controllers/UserController.php
<?php

class UserController extends BaseController
{
	public function index()
	{
		$users = User::orderBy('name', 'asc')->paginate(2);

		return View::make('users.index', compact('users'));
	}

	public function create()
	{
		return View::make('users.create');
	}

	public function store()
	{
		// Validation rules
		$rules = [
			'email'     => 'required|unique:users,email|email',
			'name'      => 'required|max:150',
			'password'  => 'required|min:8|confirmed'
		];

		// Get all input from form
		$input = Input::all();

		// Custom validation messages
		$messages = [
			'email.unique'   => 'Emel telah digunakan. Sila pilih email yang lain.',
			'email.required' => 'Sila isikan alamat emel yang sah.',
			'email.email'    => 'Sila emel menepati format.',

			'name.required'  => 'Sila isikan nama penuh anda.',
			'name.max'       => 'Maksimum karakter adalah 150 sahaja.',

			'password.required'  => 'Sila isikan kata laluan anda.',
			'password.min'  => 'Kata laluan mestilah sekurang-kurangnya 8 aksara.',
		];

		$validation = Validator::make($input, $rules, $messages);

		if ($validation->fails()) {
			return Redirect::back()->withInput()->withErrors($validation);
		}

		// Encrypt user password before storing to DB
		$input['password'] = Hash::make($input['password']);

		User::create($input);

		return Redirect::to('/user');
	}

	public function edit($id)
	{
		$user = User::find($id);

		return View::make('users.edit', compact('user'));
	}

	public function update($id)
	{
		// Validation rules
		$rules = [
			'email'     => 'required|unique:users,email,'.$id.'|email',
			'name'      => 'required|max:150',
			'password'  => 'min:8|confirmed'
		];

		// Get all input from form
		$input = Input::all();

		// Custom validation messages
		$messages = [
			'email.unique'   => 'Emel telah digunakan. Sila pilih email yang lain.',
			'email.required' => 'Sila isikan alamat emel yang sah.',
			'email.email'    => 'Sila emel menepati format.',

			'name.required'  => 'Sila isikan nama penuh anda.',
			'name.max'       => 'Maksimum karakter adalah 150 sahaja.',

			'password.min'  => 'Kata laluan mestilah sekurang-kurangnya 8 aksara.',
		];

		$validation = Validator::make($input, $rules, $messages);

		if ($validation->fails()) {
			return Redirect::back()->withInput()->withErrors($validation);
		}

		// Kalau password ada isi
		if (Input::has('password')) {
			// update password
			// Encrypt user password before storing to DB
			$input['password'] = Hash::make($input['password']);
		}
		// Kalau tidak
		else {
			// tak perlu buat apa apa
			unset($input['password']);
		}

		$user = User::find($id);

		$user->update($input);

		return Redirect::to('/user');
	}

	public function delete($id)
	{
		$user = User::find($id);

		$user->delete();

		return Redirect::to('/user');
	}

}

app/views/master.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>@yield('title', 'Laravel')</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-alpha1/jquery.min.js"></script>

        <script>
            jQuery(document).ready( function() {

                jQuery('.btn-danger').click( function() {
                    if (! confirm('Adakah anda pasti ingin memadam rekod ini?')) {
                        return false;
                    }
                });

            });
        </script>
    </head>
    <body>
        <div class="container">
            @yield('content')
        </div>
    </body>
</html>

app/views/users/create.blade.php
@extends('master')

@section('title', 'Create User')

@section('content')

    {{ Form::open(['url' => 'user', 'class' => 'form-horizontal']) }}

        <p>
            {{ Form::label('name', 'Name') }}
            {{ Form::text('name', null, ['class' => 'form-control', 'id' => 'name']) }}

            @if ($errors->has('name'))
                <span class="text-danger">
                    {{ $errors->first('name') }}
                </span>
            @endif
        </p>

        <p>
            {{ Form::label('email', 'Email') }}
            {{ Form::email('email', null, ['class' => 'form-control']) }}

            @if ($errors->has('email'))
                <span class="text-danger">
                    {{ $errors->first('email') }}
                </span>
            @endif
        </p>

        <p>
            {{ Form::label('password', 'Password') }}
            {{ Form::password('password', ['class' => 'form-control']) }}

            @if ($errors->has('password'))
                <span class="text-danger">
                    {{ $errors->first('password') }}
                </span>
            @endif
        </p>

        <p>
            {{ Form::label('password_confirmation', 'Repeat Password') }}
            {{ Form::password('password_confirmation', ['class' => 'form-control']) }}
        </p>

        <p>
            {{ Form::submit('Save User', ['class' => 'btn btn-primary']) }}
        </p>

    {{ Form::close() }}

@stop

app/views/users/edit.blade.php
@extends('master')

@section('title', 'Create User')

@section('content')

    {{ Form::model($user,
        [
            'route' => [
                'user.update', $user->id
            ],
            'method' => 'PUT',
            'class' => 'form-horizontal'
        ]) }}

        <p>
            {{ Form::label('name', 'Name') }}
            {{ Form::text('name', $user->name, ['class' => 'form-control', 'id' => 'name']) }}

            @if ($errors->has('name'))
                <span class="text-danger">
                    {{ $errors->first('name') }}
                </span>
            @endif
        </p>

        <p>
            {{ Form::label('email', 'Email') }}
            {{ Form::email('email', $user->email, ['class' => 'form-control']) }}

            @if ($errors->has('email'))
                <span class="text-danger">
                    {{ $errors->first('email') }}
                </span>
            @endif
        </p>

        <p>
            {{ Form::label('password', 'Password') }}
            {{ Form::password('password', ['class' => 'form-control']) }}

            @if ($errors->has('password'))
                <span class="text-danger">
                    {{ $errors->first('password') }}
                </span>
            @endif
        </p>

        <p>
            {{ Form::label('password_confirmation', 'Repeat Password') }}
            {{ Form::password('password_confirmation', ['class' => 'form-control']) }}
        </p>

        <p>
            {{ Form::submit('Save User', ['class' => 'btn btn-primary']) }}
        </p>

    {{ Form::close() }}

@stop

app/views/users/index.blade.php
@extends('master')

@section('title', 'User List')

@section('content')
    <h1>User List</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach ($users as $user)
            <tr>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>
                    <a href="{{ URL::route('user.edit', $user->id) }}" class="btn btn-xs btn-warning">
                        Edit
                    </a>

                    <a href="{{ URL::route('user.delete', $user->id) }}" class="btn btn-xs btn-danger">
                        Delete
                    </a>

                </td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3">
                    {{ $users->links() }}
                </td>
            </tr>
        </tfoot>
    </table>
@stop